apiVersion: v1
kind: Secret
metadata:
  name: db-auth
  namespace: default
type: Opaque
data:
  username: ZGItdXNlcg==
  password: bXlzZWNyZXRwYXNzd29yZA==
  database: cG9zdGdyZXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: default
  labels:
    run: test-app
spec:
  selector:
    matchLabels:
      run: test-app
  replicas: 1
  template:
    metadata:
      labels:
        run: test-app
    spec:
      containers:
      - name: test-app
        image: dnalencastre/fi-ops-test-app:1.0.0
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRESQL_HOST
            value: "localhost"
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: db-auth
                key: username
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-auth
                key: password
        resources:
          requests:
            memory: "10Mi"
            cpu:    "5m"
          limits:
            memory: "20Mi"
            cpu:    "10m"
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL Auth Proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
        args:
          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "--private-ip"
          # Enable structured logging with LogEntry format:
          - "--structured-logs"
          # Replace DB_PORT with the port the proxy should listen on
          - "--port=5432"
          # Replace the line below with the SQL instance "Connection Name"
          - "silent-wharf-383312:us-east1:fi-ops-test-db"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: sa-secret-volume
          mountPath: /secrets/
          readOnly: true
        resources:
          requests:
            memory: "10Mi"
            cpu:    "5m"
          limits:
            memory: "30Mi"
            cpu:    "20m"
      volumes:
      - name: sa-secret-volume
        secret:
          secretName: google-application-credentials
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: test-app
  name: test-app-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: test-app
  type: LoadBalancer