apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    run: test-app
spec:
  selector:
    matchLabels:
      run: test-app
  replicas: 1
  template:
    metadata:
      labels:
        run: test-app
    spec:
      containers:
      - name: test-app
        image: dnalencastre/fi-ops-test-app:0.0.1 
